# Generated by Django 5.1.3 on 2024-12-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gullar',
            old_name='tur',
            new_name='turlar',
        ),
        migrations.RemoveField(
            model_name='gullar',
            name='rasm',
        ),
    ]
